version: "3.9"
services:
  web:
    build: .
    env_file:
      - conf.env
    restart: unless-stopped
    expose: ["8000"]
    ports:
      - 8000:8000
    volumes:
      - ./render_templates:/render_templates
      - ./uploads:/uploads
